### ISSUE TITLE
bad spel

### ISSUE THREAD

**Issue by ksu-tech** [AkeBoss-tech/chessEngine#3]
engine is spel wronge

**Comment by ksu-tech** [comment]
akeboss fix!1!!!!!1111!

**Comment by ksu-tech** [comment]
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by AkeBoss-tech** [comment]
No i wont

**Comment by AkeBoss-tech** [comment]
my speeling is god what are u taking about

**Comment by ksu-tech** [comment]
BADE SPEEL NUUB
