### ISSUE TITLE
Game won't run on macos

### ISSUE THREAD

**Issue by Mootbing** [AkeBoss-tech/chessEngine#5]
I used pip3 install pygame and ran the mainPieces.py. I was going to try to help you by moving most of the icons into the ./icons/ folder, but the game won't run at all.

System:

![image](https://user-images.githubusercontent.com/50122069/97095890-48798a00-1633-11eb-90c8-c9831f2b7aaa.png)

the log:

```bash
MookBook:chess cowland$ python3 main.py
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
2020-10-24 19:55:26.571 Python[7054:2930255] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to (null)
Unable to obtain graphics context for NSWindow (Mojave behavior)
Unable to obtain graphics context for NSWindow (Mojave behavior)
```

it just freezes after the "Unable to obtain graphics context for NSWindow (Mojave behavior)" error message

**Comment by ksu-tech** [comment]
uh oh now all of the future mac os users wont be able to use this engine
