### ISSUE TITLE
chromebok suport

### ISSUE THREAD

**Issue by ksu-tech** [AkeBoss-tech/chessEngine#6]
can i play this on me chromebok

**Comment by ksu-tech** [comment]
me've got nothing to do in these boring hours of free time

**Comment by ksu-tech** [comment]
oi've got nothing to do after i finish eatin me lunch

**Comment by ksu-tech** [comment]
oi've got an hour of free time

**Comment by AkeBoss-tech** [comment]
ok
its not done yet though
to be honest i kinda forgot about it
